### ISSUE TITLE
SLE

### ISSUE THREAD

**Issue by RX28666** [VITA-Group/Large_Scale_GCN_Benchmarking#4]
Hello,

Thanks for your interesting work! I have a question about SLE, after getting new pseudo labels, do I need to reset the parameters and retrain the model or just need to keep training the current layer's model on the data with added pseudo labels? Thanks

**Comment by vermouthdky** [comment]
Hi, as described in our paper, we continue training the previous MLP in the next hop (iteration).

**Comment by RX28666** [comment]
Thanks for your response!
