### ISSUE TITLE
label leakage due to shallow copy

### ISSUE THREAD

**Issue by XiaoxinHe** [VITA-Group/Large_Scale_GCN_Benchmarking#5]
Hi,

"pseudo_split_masks = split_masks" in 
https://github.com/VITA-Group/Large_Scale_GCN_Benchmarking/blob/1247272640e11e98e1d1c92b1ba1369e9d089e83/Precomputing/Ensembling/EnGCN.py#L91
and
https://github.com/VITA-Group/Large_Scale_GCN_Benchmarking/blob/1247272640e11e98e1d1c92b1ba1369e9d089e83/Precomputing/Ensembling/EnGCN.py#L91
is a shallow copy, which means that the modification made to pseudo_split_masks will be applied to split_masks also. 

This might be problematic when:
https://github.com/VITA-Group/Large_Scale_GCN_Benchmarking/blob/1247272640e11e98e1d1c92b1ba1369e9d089e83/Precomputing/Ensembling/EnGCN.py#L128
            pseudo_split_masks["train"] = pseudo_split_masks["train"].logical_or(
                SLE_mask
            )
            pseudo_labels[SLE_mask] = SLE_pred
            pseudo_labels[split_masks["train"]] = y[split_masks["train"]]
here split_masks has been modified (because of the shallow copy mentioned above), which is identical to pseudo_split_masks, and therefore leaks the true labels.

If we use deepcopy instead,
import copy
pseudo_split_masks = copy.deepcopy(split_masks)

The accuracy on ogbn-arxiv is 71.9873 (not as good as the reported one 77.9829 ± 0.0660) with the same hyperparameters in [the script file](https://github.com/VITA-Group/Large_Scale_GCN_Benchmarking/blob/1247272640e11e98e1d1c92b1ba1369e9d089e83/scripts/ogbn-arxiv/EnGCN.sh).
Similar observations with ogbn-products.

Could you provides any insights about if my understanding is correct?
Thanks!

**Comment by vermouthdky** [comment]
Hi Xiaoxin, thanks for pointing out this bug. We have rerun EnGCN on the four dataset. Thus close this issue. If there is any concern, please reopen it again.
